User.destroy_all
Character.destroy_all

u1 = User.create :name => "Pete", :email => "peter_fagan@hotmail.com", :password => "chicken", :password_confirmation => "chicken"
u2 = User.create :name => "wolf", :email => "wolf@ga.co", :password => "chicken", :password_confirmation => "chicken"
u3 = User.create :name => "Badger", :email => "badger@ga.co", :password => "chicken", :password_confirmation => "chicken"

p "User count: #{User.all.count}"
p u1

Collection.destroy_all

m1 = Collection.create :user_id => u1.id
m2 = Collection.create :user_id => u2.id
m3 = Collection.create :user_id => u3.id

Race.destroy_all

# r = Race.create :name => "", :description => "", :ability_increases => "", :age => "", :alignment => "", :size => "", :speed => "", :languages => "", :features => ""

r1 = Race.create :name => "Human", :description => "In the reckonings of most worlds, humans are the youngest of the common races, late to arrive on the world scene and short-lived in comparison to dwarves, elves, and dragons. Perhaps it is because of their shorter lives that they strive to achieve as much as they can in the years they are given. Or maybe they feel they have something to prove to the elder races, and that’s why they build their mighty empires on the foundation of conquest and trade. Whatever drives them, humans are the innovators,the achievers,and the pioneers of the worlds. <br />
With their penchant for migration and conquest, humans are more physically diverse than other common races. There is no typical human. An individual can stand from 5 feet to a little over 6 feet tall and weigh from 125 to 250 pounds. Human skin shades range from nearly black to very pale, and hair colors from black to blond (curly, kinky, or straight); males might sport facial hair that is sparse or thick. A lot of humans have a dash of nonhuman blood, revealing hints of elf, orc,or other lineages. Humans reach adulthood in their late teens and rarely live even a single century.
", :ability_increases => "Str:1,Dex:1,Con:1,Int:1,Wis:1,Cha:1", :age => "Humans reach adulthood in their late teens and live less than a century.", :alignment => "Humans tend toward no particular alignment. The best and the worst are found among them.", :size => "Humans vary widely in height and build, from barely 5 feet to well over 6 feet tall. Regardless of your position in that range, your size is Medium.", :speed => "Your base walking speed is 30 feet.", :languages => "You can speak, read, and write Common and one extra language of your choice. Humans typically learn the languages of other peoples they deal with, including obscure dialects. They are fond of sprinkling their speech with words borrowed from other tongues: Orc curses, Elvish musical expressions, Dwarvish military phrases, and so on.", :features => "No additional Features"
r2 = Race.create :name => "High Elf", :description => "Elves are a magical people of otherworldly grace, living in the world but not entirely part of it. They live in places of ethereal beauty, in the midst of ancient forests or in silvery spires glittering with faerie light, where soft music drifts through the air and gentle fragrances waft on the breeze. Elves love nature and magic, art and artistry, music and poetry, and the good things of the world. <br />
As a high elf, you have a keen mind and a mastery of at least the basics of magic. <br />
With their unearthly grace and fine features, elves appear hauntingly beautiful to humans and members of many other races. They are slightly shorter than humans on average, ranging from well under 5 feet tall to just over 6 feet. They are more slender than humans, weighing only 100 to 145 pounds. Males and females are about the same height, and males are only marginally heavier than females. <br />
The sun elves of Faerun (also called gold elves or sunrise elves) have bronze skin and hair of copper, black, or golden blond. Their eyes are golden, silver, or black. Moon elves (also called silver elves or gray elves) are much paler, with alabaster skin som etim es tinged with blue. They often have hair of silver-white, black, or blue, but various shades of blond, brown, and red are not uncommon. Their eyes are blue or green and flecked with gold.", :ability_increases => "Dex:2,Int:1", :age => "Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old.", :alignment => "Elves love freedom, variety, and self-expression, so they lean strongly toward the gentler aspects of chaos. They value and protect others’ freedom as well as their own, and they are more often good than not.", :size => "Elves range from under 5 to over 6 feet tall and have slender builds. Your size is Medium.", :speed => "Your base walking speed is 30 feet.", :languages => "You can speak, read, and write Common and Elvish. Elvish is fluid, with subtle intonations and intricate grammar. Elven literature is rich and varied, and their songs and poems are famous among other races. Many bards learn their language so they can add Elvish ballads to their repertoires.", :features => " <br />
-Darkvision. Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray. <br />
-Keen Senses. You have proficiency in the Perception skill.<br />
-Fey Ancestry. You have advantage on saving throws against being charmed, and magic can’t put you to sleep. <br />
-Trance. Elves don’t need to sleep. Instead, they meditate deeply, remaining semiconscious, for 4 hours a day. (The Common word for such meditation is “trance.”) While meditating, you can dream after a fashion; such dreams are actually mental exercises that have become reflexive through years of practice. After resting in this way, you gain the same benefit that a human does from 8 hours of sleep. <br />
-Elf Weapon Training. You have proficiency with the longsword, shortsword, shortbow, and longbow. <br />
-Cantrip. You know one cantrip of your choice from the wizard spell list. Intelligence is your spellcasting ability for it. <br />
-Extra Language. You can speak, read, and write one extra language of your choice."
r3 = Race.create :name => "Wood Elf", :description => "Elves are a magical people of otherworldly grace, living in the world but not entirely part of it. They live in places of ethereal beauty, in the midst of ancient forests or in silvery spires glittering with faerie light, where soft music drifts through the air and gentle fragrances waft on the breeze. Elves love nature and magic, art and artistry, music and poetry, and the good things of the world. <br />
As a wood elf, you have keen senses and intuition, and your fleet feet carry you quickly and stealthily through your native forests. <br />
With their unearthly grace and fine features, elves appear hauntingly beautiful to humans and members of many other races. They are slightly shorter than humans on average, ranging from well under 5 feet tall to just over 6 feet. They are more slender than humans, weighing only 100 to 145 pounds. Males and females are about the same height, and males are only marginally heavier than females. <br />
Wood elves’ skin tends to be copperish in hue, sometimes with traces of green. Their hair tends toward browns and blacks, but it is occasionally blond or copper-colored. Their eyes are green, brown, or hazel.", :ability_increases => "Dex:2,Wis:1", :age => "Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old.", :alignment => "Elves love freedom, variety, and self-expression, so they lean strongly toward the gentler aspects of chaos. They value and protect others’ freedom as well as their own, and they are more often good than not.", :size => "Elves range from under 5 to over 6 feet tall and have slender builds. Your size is Medium.", :speed => "Fleet of Foot. Your base walking speed is 35 feet", :languages => "You can speak, read, and write Common and Elvish. Elvish is fluid, with subtle intonations and intricate grammar. Elven literature is rich and varied, and their songs and poems are famous among other races. Many bards learn their language so they can add Elvish ballads to their repertoires.", :features => " <br />
-Darkvision. Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray. <br />
-Keen Senses. You have proficiency in the Perception skill. <br />
-Fey Ancestry. You have advantage on saving throws against being charmed, and magic can’t put you to sleep. <br />
-Trance. Elves don’t need to sleep. Instead, they meditate deeply, remaining semiconscious, for 4 hours a day. (The Common word for such meditation is “trance.”) While meditating, you can dream after a fashion; such dreams are actually mental exercises that have become reflexive through years of practice. After resting in this way, you gain the same benefit that a human does from 8 hours of sleep. <br />
-Elf Weapon Training. You have proficiency with the longsword, shortsword, shortbow, and longbow. <br />
-Mask ofthe Wild. You can attempt to hide even when you are only lightly obscured by foliage, heavy rain, falling snow, mist, and other natural phenomena."
r4 = Race.create :name => "Hill Dwarf", :description => "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal. Though they stand well under 5 feet tall, dwarves are so broad and compact that they can weigh as much as a human standing nearly two feet taller. Their courage and endurance are also easily a match for any of the larger folk. <br />
Dwarven skin ranges from deep brown to a paler hue tinged with red, but the most common shades are light brown or deep tan, like certain tones of earth. Their hair, worn long but in simple styles, is usually black, gray, or brown, though paler dwarves often have red hair. Male dwarves value their beards highly and groom them carefully. <br />
Dwarves can live to be more than 400 years old, so the oldest living dwarves often remember a very different world. For example, some of the oldest dwarves living in Citadel Felbarr (in the world of the Forgotten Realms) can recall the day, more than three centuries ago, when orcs conquered the fortress and drove them into an exile that lasted over 250 years. This longevity grants them a perspective on the world that shorter-lived races such as humans and halflings lack. <br />
Dwarves are solid and enduring like the mountains they love, weathering the passage of centuries with stoic endurance and little change. They respect the traditions of their clans, tracing their ancestry back to the founding of their most ancient strongholds in the youth of the world, and don't abandon those traditions lightly. Part of those traditions is devotion to the gods of the dwarves, who uphold the dwarven ideals of industrious labor, skill in battle, and devotion to the forge. <br />
Individual dwarves are determined and loyal, true to their word and decisive in action, sometimes to the point of stubbornness. Many dwarves have a strong sense of justice, and they are slow to forget wrongs they have suffered. A wrong done to one dwarf is a wrong done to the dwarf’s entire clan, so what begins as one dwarf’s hunt for vengeance can become a full-blown clan feud. <br/ >
As a hill dwarf, you have keen senses, deep intuition, and remarkable resilience. The gold dwarves of Faerun in their mighty southern kingdom are hill dwarves", :ability_increases => "Con:2,Wis:1", :age => "Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.", :alignment => "Most dwarves are lawful, believing firmly in the benefits of a well-ordered society. They tend toward good as well, with a strong sense of fair play and a belief that everyone deserves to share in the benefits of a just order.", :size => "Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size is Medium.", :speed => "Your base walking speed is 25 feet. Your speed is not reduced by wearing heavy armor.", :languages => "You can speak, read, and write Common and Dwarvish. Dwarvish is full of hard consonants and guttural sounds, and those characteristics spill over into whatever other language a dwarf might speak.", :features => " <br />
-Darkvision. Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray. <br />
-Dwarven Resilience. You have advantage on saving throws against poison, and you have resistance against poison damage. <br />
-Dwarven Combat Training. You have proficiency with the battleaxe, handaxe, throwing hammer, and warhammer. <br />
-Tool Proficiency. You gain proficiency with the artisan’s tools of your choice: smith’s tools, brewer’s supplies, or mason’s tools. <br />
-Stonecunning. Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus. <br />
-Dwarven Toughness. Your hit point maximum increases by 1, and it increases by 1 every time you gain a level."
r5 = Race.create :name => "Mountain Dwarf", :description => "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal. Though they stand well under 5 feet tall, dwarves are so broad and compact that they can weigh as much as a human standing nearly two feet taller. Their courage and endurance are also easily a match for any of the larger folk. <br />
Dwarven skin ranges from deep brown to a paler hue tinged with red, but the most common shades are light brown or deep tan, like certain tones of earth. Their hair, worn long but in simple styles, is usually black, gray, or brown, though paler dwarves often have red hair. Male dwarves value their beards highly and groom them carefully. <br />
Dwarves can live to be more than 400 years old, so the oldest living dwarves often remember a very different world. For example, some of the oldest dwarves living in Citadel Felbarr (in the world of the Forgotten Realms) can recall the day, more than three centuries ago, when orcs conquered the fortress and drove them into an exile that lasted over 250 years. This longevity grants them a perspective on the world that shorter-lived races such as humans and halflings lack. <br />
Dwarves are solid and enduring like the mountains they love, weathering the passage of centuries with stoic endurance and little change. They respect the traditions of their clans, tracing their ancestry back to the founding of their most ancient strongholds in the youth of the world, and don't abandon those traditions lightly. Part of those traditions is devotion to the gods of the dwarves, who uphold the dwarven ideals of industrious labor, skill in battle, and devotion to the forge. <br />
Individual dwarves are determined and loyal, true to their word and decisive in action, sometimes to the point of stubbornness. Many dwarves have a strong sense of justice, and they are slow to forget wrongs they have suffered. A wrong done to one dwarf is a wrong done to the dwarf’s entire clan, so what begins as one dwarf’s hunt for vengeance can become a full-blown clan feud. <br/ >
As a mountain dwarf, you're strong and hardy, accustomed to a difficult life in rugged terrain. You’re probably on the tall side (for a dwarf), and tend toward lighter coloration. The shield dwarves of northern Faerun are mountain dwarves.", :ability_increases => "Str:2,Con:2", :age => "Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.", :alignment => "Most dwarves are lawful, believing firmly in the benefits of a well-ordered society. They tend toward good as well, with a strong sense of fair play and a belief that everyone deserves to share in the benefits of a just order.", :size => "Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size is Medium.", :speed => "Your base walking speed is 25 feet. Your speed is not reduced by wearing heavy armor.", :languages => "You can speak, read, and write Common and Dwarvish. Dwarvish is full of hard consonants and guttural sounds, and those characteristics spill over into whatever other language a dwarf might speak.", :features => " <br />
-Darkvision. Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray. <br />
-Dwarven Resilience. You have advantage on saving throws against poison, and you have resistance against poison damage. <br />
-Dwarven Combat Training. You have proficiency with the battleaxe, handaxe, throwing hammer, and warhammer. <br />
-Dwarven Armor Training. You have proficiency with light and medium armor.<br />
-Tool Proficiency. You gain proficiency with the artisan’s tools of your choice: smith’s tools, brewer’s supplies, or mason’s tools. <br />
-Stonecunning. Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus."
r6 = Race.create :name => "Lightfoot Halfling", :description => "The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense. Standing about 3 feet tall, they appear relatively harmless and so have managed to survive for centuries in the shadow of empires and on the edges of wars and political strife. They are inclined to be stout, weighing between 40 and 45 pounds. <br />
Halflings’ skin ranges from tan to pale with a ruddy cast, and their hair is usually brown or sandy brown and wavy. They have brown or hazel eyes. Halfling men often sport long sideburns, but beards are rare among them and mustaches even more so. They like to wear simple, comfortable, and practical clothes, favoring bright colors. <br />
Halfling practicality extends beyond their clothing. They’re concerned with basic needs and simple pleasures and have little use for ostentation. Even the wealthiest ofhalflings keep their treasures locked in a cellar rather than on display for all to see. They have a knack for finding the most straightforward solution to a problem, and have little patience for dithering. <br />
Halflings are an affable and cheerful people. They cherish the bonds of family and friendship as well as the comforts of hearth and home, harboring few dreams of gold or glory. Even adventurers among them usually venture into the world for reasons of community, friendship, wanderlust, or curiosity. They love discovering new things, even simple things, such as an exotic food or an unfamiliar style of clothing. <br />
Halflings are easily moved to pity and hate to see any living thing suffer. They are generous, happily sharing what they have even in lean times. <br />
As a lightfoot halfling, you can easily hide from notice, even using other people as cover. You’re inclined to be affable and get along well with others. In the Forgotten Realms, lightfoot halflings have spread the farthest and thus are the most common variety.
Lightfoots are more prone to wanderlust than other halflings, and often dwell alongside other races or take up a nomadic life.", :ability_increases => "Dex:2,Cha:1", :age => "A halfling reaches adulthood at the age of 20 and generally lives into the middle of his or her second century.", :alignment => "Most halflings are lawful good. As a rule, they are good-hearted and kind, hate to see others in pain, and have no tolerance for oppression. They are also very orderly and traditional, leaning heavily on
the support of their community and the comfort of their old ways.", :size => "Halflings average about 3 feet tall and weigh about 40 pounds. Your size is Small.", :speed => "Your base walking speed is 25 feet.", :languages => "You can speak, read, and write Common and Halfling. The Halfling language isn’t secret, but halflings are loath to share it with others. They write very little, so they don’t have a rich body of literature. Their oral tradition, however, is very strong. Almost all halflings speak Common to converse with the people in whose lands they dwell or through which they
are traveling.", :features => " <br />
-Lucky. When you roll a 1 on an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll. <br />
-Brave. You have advantage on saving throws against being frightened. <br />
-Halfling Nimbleness. You can move through the space of any creature that is of a size larger than yours. <br />
-Naturally Stealthy. You can attempt to hide even when you are obscured only by a creature that is at least one size larger than you."
r7 = Race.create :name => "Stout Halfling", :description => "The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense. Standing about 3 feet tall, they appear relatively harmless and so have managed to survive for centuries in the shadow of empires and on the edges of wars and political strife. They are inclined to be stout, weighing between 40 and 45 pounds. <br />
Halflings’ skin ranges from tan to pale with a ruddy cast, and their hair is usually brown or sandy brown and wavy. They have brown or hazel eyes. Halfling men often sport long sideburns, but beards are rare among them and mustaches even more so. They like to wear simple, comfortable, and practical clothes, favoring bright colors. <br />
Halfling practicality extends beyond their clothing. They’re concerned with basic needs and simple pleasures and have little use for ostentation. Even the wealthiest ofhalflings keep their treasures locked in a cellar rather than on display for all to see. They have a knack for finding the most straightforward solution to a problem, and have little patience for dithering. <br />
Halflings are an affable and cheerful people. They cherish the bonds of family and friendship as well as the comforts of hearth and home, harboring few dreams of gold or glory. Even adventurers among them usually venture into the world for reasons of community, friendship, wanderlust, or curiosity. They love discovering new things, even simple things, such as an exotic food or an unfamiliar style of clothing. <br />
Halflings are easily moved to pity and hate to see any living thing suffer. They are generous, happily sharing what they have even in lean times. <br />
As a stout halfling, you’re hardier than average and have some resistance to poison. Some say that stouts have dwarven blood. In the Forgotten Realms, these halflings are called stronghearts, and they’re most common
in the south.", :ability_increases => "Dex:2,Con:1", :age => "A halfling reaches adulthood at the age of 20 and generally lives into the middle of his or her second century.", :alignment => "Most halflings are lawful good. As a rule, they are good-hearted and kind, hate to see others in pain, and have no tolerance for oppression. They are also very orderly and traditional, leaning heavily on
the support of their community and the comfort of their old ways.", :size => "Halflings average about 3 feet tall and weigh about 40 pounds. Your size is Small.", :speed => "Your base walking speed is 25 feet.", :languages => "You can speak, read, and write Common and Halfling. The Halfling language isn’t secret, but halflings are loath to share it with others. They write very little, so they don’t have a rich body of literature. Their oral tradition, however, is very strong. Almost all halflings speak Common to converse with the people in whose lands they dwell or through which they
are traveling.", :features => " <br />
-Lucky. When you roll a 1 on an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll. <br />
-Brave. You have advantage on saving throws against being frightened. <br />
-Halfling Nimbleness. You can move through the space of any creature that is of a size larger than yours. <br />
-Stout Resilience. You have advantage on saving throws against poison, and you have resistance against poison damage."

Profession.destroy_all

# c = Profession.create :name => "", :description => "", :hit_dice => "", :saving_throw => "", :prof_skills => "", :start_hit_points => "", :start_prof_bonus => "", :start_features => "", :start_equipment =>

c1 = Profession.create :name => "Fighter", :description => "Fighters learn the basics of all combat styles. Every fighter can swing an axe, fence with a rapier, wield a longsword or a greatsword, use a bow, and even trap foes in a net with some degree of skill. Likewise, a fighter is adept with shields and every form of armor. Beyond that basic degree of familiarity, each fighter specializes in a certain style of combat. Some concentrate on archery, some on fighting with two weapons at once, and some on augmenting their martial skills with magic. This combination of broad general ability and extensive specialization makes fighters superior combatants
on battlefields and in dungeons alike.", :hit_dice => "d10", :saving_throw => "Str, Con or Dex", :prof_skills => "Blacksmith, animal handling", :start_hit_points => "10", :start_prof_bonus => "+2", :start_features => "All armor, shields, simple and martial weapons. <br />
Fighting Style: You adopt a particular style of fighting as your specialty. Choose one of the following options. <br />
-Archery. You gain a +2 bonus to attack rolls you make with ranged weapons. <br />
-Defense. While you are wearing armor, you gain a +1 bonus to AC. <br />
-Dueling. When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon. <br />
-Great Weapon Fighting. When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll, even if the new roll is a 1 or a 2. The weapon must have the two-handed or versatile property for you to gain this benefit. <br />
-Protection. When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll. You must be wielding a shield. <br />
-Two-Weapon Fighting. When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack. <br />
-Second Wind: You have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use a bonus action to regain hit points equal to 1d10 + your fighter level. Once you use this feature, you must finish a short or long rest before you can use it again.", :start_equipment => "You start with the following equipment, in addition to the equipment granted by your background: <br />
• (a) chain mail or (b) leather, longbow, and 20 arrows <br />
• (a) a martial weapon and a shield or (b) two martial weapons <br />
• (a) a light crossbow and 20 bolts or (b) two handaxes <br />
• (a) a dungeoneer’s pack or (b) an explorer’s pack"
c2 = Profession.create :name => "Rogue", :description => "A scoundrel and stealthy warrior who uses stealth and trickery to overcome obstacles and enemies.", :hit_dice => "d8", :saving_throw => "Dex, Int", :prof_skills => "lockpicking, pickpocket", :start_hit_points => "8", :start_prof_bonus => "+2", :start_features => "Light Armor Proficiency. Simple Weapons, Hand crossbows, Longswords, Rapiers, Shortswords Proficiencies. <br />
-Sneak Attack: You know how to strike subtly and exploit a foe’s distraction. Once per turn, you can deal extra damage to one creature you hit with an attack if you have advantage on the attack roll. The attack must use a finesse or a ranged weapon. <br />
-Thieves' Cant: During your rogue training you learned thieves’ cant, a secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation. Only another creature that knows thieves’ cant understands such messages. It takes four times longer to convey such a message than it does to speak the same idea plainly. In addition, you understand a set of secret signs and symbols used to convey short, simple messages, such as whether an area is dangerous or the territory of a thieves’ guild, whether loot is nearby, or whether the people in an area are easy marks or will provide a safe house for thieves on the run. <br />
-Cunning Action: Starting at your second level, your quick thinking and agility allow you to move and act quickly. You can take a bonus action on each of your turns in combat. This action can be used only to take the Dash, Disengage, or Hide action.", :start_equipment => "You start with the following equipment, in addition to the equipment granted by your background: <br />
• (a) a rapier or (b) a shortsword <br />
• (a) a shortbow and quiver of 20 arrows or (b) a shortsword <br />
• (a) a burglar’s pack, (b) a dungeoneer’s pack, or (c) an explorer’s pack <br />
• Leather armor, two daggers, and thieves’ tools"
c3 = Profession.create :name => "Wizard", :description => "Wizards are supreme magic-users, defined and united as a class by the spells they cast. Drawing on the subtle weave of magic that permeates the cosmos, wizards cast spells of explosive fire, arcing lightning, subtle deception, and brute-force mind control. Their magic conjures monsters from other planes of existence, glimpses the future, or turns slain foes into zombies. Their mightiest spells change one substance into another, call meteors down from the sky, or open portals to other worlds. <br />
Though the casting of a typical spell requires merely the utterance of a few strange words, fleeting gestures, and sometimes a pinch or clump of exotic materials, these surface components barely hint at the expertise attained after years of apprenticeship and countless hours of study. <br />
Wizards live and die by their spells. Everything else is secondary. They learn new spells as they experiment and grow in experience. They can also learn them from other wizards, from ancient tomes or inscriptions, and from ancient creatures (such as the fey) that are steeped in magic. <br />
Wizards’ lives are seldom mundane. The closest a wizard is likely to come to an ordinary life is working as a sage or lecturer in a library or university, teaching others the secrets of the multiverse. Other wizards sell their services as diviners, serve in military forces, or pursue lives of crime or domination. <br />
But the lure of knowledge and power calls even the most unadventurous wizards out of the safety of their libraries and laboratories and into crumbling ruins and lost cities. Most wizards believe that their counterparts in ancient civilizations knew secrets of magic that have been lost to the ages, and discovering those secrets could unlock the path to a power greater than any magic available in the present age.", :hit_dice => "d6", :saving_throw => "Int, Wis", :prof_skills => "Choose two from Arcana, History, Insight,
Investigation, Medicine, and Religion", :start_hit_points => "6", :start_prof_bonus => "+2", :start_features => "No armor proficiencies. Dagger, dart, sling, quarterstaff, Light crossbow weapon proficiencies. <br />
-Cantrips: At 1st level, you know three cantrips of your choice from the wizard spell list. You learn additional wizard cantrips of your choice at higher levels. <br />
-Spellbook: At 1st level, you have a spellbook containing six 1st-level wizard spells of your choice. <br />
-Spellcasting Ability: Intelligence is your spellcasting ability for your wizard spells, since you learn your spells through dedicated study and memorization. You use your Intelligence whenever a spell refers to your spellcasting ability. <br />
In addition, you use your Intelligence modifier when setting the saving throw DC for a wizard spell you cast and when making an attack roll with one. <br />
Spell save DC = 8 + your proficiency bonus + your Intelligence modifier <br />
Spell attack modifier = your proficiency bonus + your intelligence modifier <br />
-Ritual Casting: You can cast a wizard spell as a ritual if that spell has the ritual tag and you have the spell in your spellbook. You don't need to have the spell prepared. <br />
-Spellcasting Focus: You can use an arcane focus as a spellcasting focus for your wizard spells. <br />
-Arcane Recovery: You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher.
", :start_equipment => "You start with the following equipment, in addition to the equipment granted by your background: <br />
• (a) a quarterstaff or (b) a dagger <br />
• (a) a component pouch or (b) an arcane focus <br />
• (a) a scholar’s pack or (b) an explorer’s pack <br />
• A spellbook"
c4 = Profession.create :name => "Cleric", :description => "Clerics are intermediaries between the mortal world and the distant planes of the gods. As varied as the gods they serve, clerics strive to embody the handiwork of their deities. No ordinary priest, a cleric is imbued with divine magic. <br />
Divine magic, as the name suggests, is the power of the gods, flowing from them into the world. Clerics are conduits for that power, manifesting it as miraculous effects. The gods don’t grant this power to everyone who seeks it, but only to those chosen to fulfill a high calling. <br />
Harnessing divine magic doesn’t rely on study or training. A cleric might learn formulaic prayers and ancient rites, but the ability to cast cleric spells relies on devotion and an intuitive sense of a deity’s wishes. <br />
Clerics combine the helpful magic of healing and inspiring their allies with spells that harm and hinder foes. They can provoke awe and dread, lay curses of plague or poison, and even call down flames from heaven to consume their enemies. For those evildoers who will benefit most from a mace to the head, clerics depend on their combat training to let them wade into melee with the power of the gods on their side. <br />
Not every acolyte or officiant at a temple or shrine is a cleric. Some priests are called to a simple life of temple service, carrying out their gods’ will through prayer and sacrifice, not by magic and strength of arms. In some cities, priesthood amounts to a political office, viewed as a stepping stone to higher positions of authority and involving no communion with a god at all. True clerics are rare in most hierarchies. <br />
When a cleric takes up an adventuring life, it is usually because his or her god demands it. Pursuing the goals of the gods often involves braving dangers beyond the walls of civilization, smiting evil or seeking holy relics in ancient tombs. Many clerics are also expected to protect their deities’ worshipers, which can mean fighting rampaging orcs, negotiating peace between warring nations, or sealing a portal that would allow a demon prince to enter the world. <br />
Most adventuring clerics maintain some connection to established temples and orders of their faiths. A temple might ask for a cleric’s aid, or a high priest might be in a position to demand it.", :hit_dice => "d8", :saving_throw => "Wis, Cha", :prof_skills => "Choose two from History, Insight, Medicine, Persuasion, and Religion", :start_hit_points => "8", :start_prof_bonus => "", :start_features => "Light armor, medium armor, shield proficiencies. All simple weapon proficiencies. <br />
-Spellcasting: As a conduit for divine power, you can cast cleric spells. At 1st level, you know three cantrips of your choice from the cleric spell list.<br />
-Spellcasting Ability: Wisdom is your spellcasting ability for your cleric spells. The power of your spells comes from your devotion to your deity. You use your Wisdom whenever a cleric spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for a cleric spell you cast and when making an attack roll with one.<br />
Spell save DC = 8 + your proficiency bonus + your Wisdom modifier. <br />
Spell attack modifier = your proficiency bonus + your Wisdom modifier. <br />
-Ritual Casting: You can cast a cleric spell as a ritual if that spell has the ritual tag and you have the spell prepared.
-Spellcasting Focus: You can use a holy symbol as a spellcasting focus for your cleric spells.
-Divine Domain: Choose one domain related to your deity: Knowledge, Life, Light, Nature, Tempest, Trickery, or War. Each domain is detailed at the end of the class description, and each one provides examples of gods associated with it. Your choice grants you domain spells and other features when you choose it at 1st level.<br />
-Domain Spells: Each domain has a list of spells—its domain spells— that you gain at the cleric levels noted in the domain description. Once you gain a domain spell, you always have it prepared, and it doesn’t count against the number of spells you can prepare each day. If you have a domain spell that doesn’t appear on the cleric spell list, the spell is nonetheless a cleric spell for you.", :start_equipment => "You start with the following equipment, in addition to the equipment granted by your background: <br />
• (a) a mace or (b) a warhammer (if proficient) <br />
• (a) scale mail, (b) leather armor, or (c) chain mail (if proficient) <br />
• (a) a light crossbow and 20 bolts or (b) any simple weapon <br />
• (a) a priest’s pack or (b) an explorer’s pack <br />
• A shield and a holy symbol"

Background.destroy_all

# b = Background.create :name => "", :description => "", :background_skills => "", :background_languages => "", :background_equipment => "", :feature => "", :characteristics => "", :personality_trait => ["", "", "", "", "", "", "", ""].sample, :ideal => ["", "", "", "", "", ""].sample, :bond => ["", "", "", "", "", "" ].sample, :flaw => ["", "", "", "", "", ""].sample

b1 = Background.create :name => "Acolyte", :description => "You have spent your life in the service of a temple to a specific god or pantheon of gods.<br />
You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine.<br />
You are not necessarily a cleric - performing sacred rites is not the same thing as channeling divine power.<br />
Choose a god, a pantheon of gods, or some other quasi-divine being and work with your DM to detail the nature of your religious service.<br />
Were you a lesser functionary in a temple, raised from childhood to assist the priests in the sacred rites?<br />
Or were you a high priest who suddenly experienced a call to serve your god in a different way?<br />
Perhaps you were the leader of a small cult outside of any established temple structure, or even an occult group that served a fiendish master that you now deny.", :background_skills => "Insight, Religion", :background_languages => "Two of your choice", :background_equipment => "A holy symbol (a gift to you when you entered the priesthood), a prayer book or prayer wheel, 5 sticks of incense, vestments, a set of common clothes, and a belt pouch containing 15 gp", :feature => "Shelter of the Faithful.<br />
As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity.<br />
You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells.<br />
Those who share your religion will support you (but only you) at a modest lifestyle.
You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there.<br />
This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home.<br />
While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple.", :characteristics => "Acolytes are shaped by their experience in temples or other religious communities. Their study of the history and tenets of their faith and their relationships to temples, shrines, or hierarchies affect their mannerisms and ideals. Their flaws might be some hidden hypocrisy or heretical idea, or an ideal or bond taken to an extreme.", :personality_trait => ["I idolize a particular hero of my faith, and constantly refer to that person’s deeds and example.", "I can find common ground between the fiercest enemies, empathizing with them and always working towards peace.", "I see omens in every event and action. The gods try to speak to us, we just need to listen.", "Nothing can shake my optimistic attitude.", "I quote (or misquote) sacred texts and proverbs in almost every situation.", "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.", "I've enjoyed fine food, drink, and high society among my temple’s elite. Rough living grates on me.", "I’ve spent so long in the temple that I have little practical experience dealing with people in the outside world."].sample, :ideal => ["Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld.", "Charity. I always try to help those in need, no matter what the personal cost.", "Change. We must help bring about the changes the gods are constantly working in the world.", "Power. I hope to one day rise to the top of my faith’s religious hierarchy.", "Faith. I trust that my deity will guide my actions, I have faith that if I work hard, things will go well.", "Aspiration. I seek to prove myself worthy of my god’s favor by matching my actions against his or her teachings."].sample, :bond => ["I would die to recover an ancient relic of my faith that was lost long ago.", "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.", "I owe my life to the priest who took me in when my parents died.", "Everything I do is for the common people.", "I will do anything to protect the temple where I served.", "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy." ].sample, :flaw => ["I judge others harshly, and myself even more severely.", "I put too much trust in those who wield power within my temple’s hierarchy.", "My piety sometimes leads me to blindly trust those that profess faith in my god.", "I am inflexible in my thinking.", "I am suspicious of strangers and expect the worst of them.", "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life."].sample
b2 = Background.create :name => "Charlatan", :description => "You have always had a way with people.<br />
You know what makes them tick, you can tease out their hearts' desires after a few minutes of conversation, and with a few leading questions you can read them like they were children's books.<br />
It’s a useful talent, and one that you’re perfectly willing to use for your advantage.
You know what people want and you deliver, or rather, you promise to deliver.
Common sense should steer people away from things that sound too good to be true, but common sense seems to be in short supply when you’re around.<br />
The bottle of pink-colored liquid will surely cure that unseemly rash, this ointment—nothing more than a bit of fat with a sprinkle of silver dust—can
restore youth and vigor, and there’s a bridge in the city that just happens to be for sale.<br />
These marvels sound implausible, but you make them sound like the real deal.<br /> Every charlatan has an angle he or she uses in preference to other schemes. " + ["I cheat at games of chance.", "I shave coins or forge documents.", "I insinuate myself into people’s lives to prey on their weakness and secure their fortunes.", "I put on new identities like clothes.", "I run sleight-of-hand cons on street corners.", "I convince people that worthless junk is worth their hard-earned money."].sample, :background_skills => "Deception, Sleight of Hand", :background_languages => "Disguise Kit, Forgery Kit", :background_equipment => "A set of fine clothes, a disguise kit, tools of the con of your choice (ten stoppered bottles filled with colored liquid, a set of weighted dice, a deck of marked cards, or a signet ring of an imaginary duke), and a belt pouch containing 15 gp", :feature => "False Identity.<br />
You have created a second identity that includes documentation, established acquaintances, and disguises that allow you to assume that persona.<br />
Additionally, you can forge documents including official papers and personal letters, as long as you have seen an example of the kind of document or the handwriting you are trying to copy.", :characteristics => "Charlatans are colorful characters who conceal their true selves behind the masks they construct.<br />
They reflect what people want to see, what they want to believe, and how they see the world.<br />
But their true selves are sometimes plagued by an uneasy conscience, an old enemy, or deep-seated trust issues.", :personality_trait => ["I fall in and out of love easily, and am always pursuing someone.", "I have a joke for every occasion, especially occasions where humor is inappropriate.", "Flattery is my preferred trick for getting what I want.", "I’m a born gambler who can't resist taking a risk for a potential payoff.", "I lie about almost everything, even when there’s no good reason to.", "Sarcasm and insults are my weapons of choice.", "I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.", "I pocket anything I see that might have some value."].sample, :ideal => ["Independence. I am a free spirit— no one tells me what to do. ", "Fairness. I never target people who can’t afford to lose a few coins. ", "Charity. I distribute the money I acquire to the people who really need it.", "Creativity. I never run the same con twice.", "Friendship. Material goods come and go. Bonds of friendship last forever.", "Aspiration. I’m determined to make something of myself."].sample, :bond => ["I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.", "I owe everything to my mentor—a horrible person who’s probably rotting in jail somewhere.", "Somewhere out there, I have a child who doesn’t know me.
I’m making the world better for him or her.", "I come from a noble family, and one day I’ll reclaim my lands and title from those who stole them from me.", "A powerful person killed someone I love. Some day soon, I’ll have my revenge.", "I swindled and ruined a person who didn’t deserve it. I seek to atone for my misdeeds but might never be able to forgive myself." ].sample, :flaw => ["I can’t resist a pretty face.", "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.", "I’m convinced that no one could ever fool me the way I fool others.", "I’m too greedy for my own good. I can’t resist taking a risk if there’s money involved.", "I can’t resist swindling people who are more powerful than me.", "I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough."].sample
b3 = Background.create :name => "Criminal", :description => "You are an experienced criminal with a history of breaking the law.<br />
You have spent a lot of time among other criminals and still have contacts within the criminal underworld.<br />
You’re far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization, and you have survived up to this point by flouting the rules and regulations of society. Variant: Spy.<br />
Although your capabilities are not much different from those of a burglar or smuggler, you learned and practiced them in a very different context: as an espionage agent.
You might have been an officially sanctioned agent of the crown, or perhaps you sold the secrets you uncovered to the highest bidder.<br />
There are many kinds of criminals, and within a thieves’ guild or similar criminal organization, individual members have particular specialties. Even criminals who operate outside of such organizations have strong preferences for certain kinds of crimes over others.<br >", :background_skills => "Deception, Stealth", :background_languages => "One type of gaming set, thieves’ tools", :background_equipment => "A crowbar, a set of dark common clothes including a hood, and a belt pouch containing 15 GP", :feature => "Criminal contact. You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals.
You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you.", :characteristics => "Criminals might seem like villains on the surface, and many of them are villainous to the core.
But some have an abundance of endearing, if not redeeming, characteristics.
There might be honor among thieves, but criminals rarely show any respect for law or authority.", :personality_trait => ["I always have a plan for what to do when things go wrong.", "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.", "The first thing I do in a new place is note the locations of everything valuable-or where such things could be hidden.", "I would rather make a new friend then a new enemy.", "I am increadibly slow to trust. Those who seem the fairest often have the most to hide.", "I don't pay attention to the risks in a situation. Never tell me the odds.", "The best way to get me to do something is to tell me I can't do it.", "I blow up at the slightest insult."].sample, :ideal => ["Honor. I don’t steal from others in the trade.", "Freedom. Chains are meant to be broken, as are those who would forge them.", "Charity. I steal from the wealthy so that I can help people in need. ", "Greed. I will do whatever it takes to become wealthy.", "People. I’m loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care.", "Redemption. There’s a spark of good in everyone."].sample, :bond => ["I’m trying to pay off an old debt I owe to a generous benefactor.", "My ill-gotten gains go to support my family.", "Something important was taken from me, and I aim to steal it back.", "I will become the greatest thief that ever lived.", "I’m guilty of a terrible crime. I hope I can redeem myself for it.", "Someone I loved died because of a mistake I made. That will never happen again." ].sample, :flaw => ["When I see something valuable, I can’t think about anything but how to steal it.", "When faced with a choice between money and my friends, I usually choose the money.", "If there’s a plan, I’ll forget it. If I don’t forget it, I’ll ignore it.", "I have a “tell” that reveals when I'm lying.", "I turn tail and run when things look bad.", "An innocent person is in prison for a crime that I committed. I’m okay with that."].sample
