User.destroy_all

u1 = User.create :name => "Pete", :email => "peter_fagan@hotmail.com", :password => "chicken", :password_confirmation => "chicken"
u2 = User.create :name => "wolf", :email => "wolf@ga.co", :password => "chicken", :password_confirmation => "chicken"
u3 = User.create :name => "Badger", :email => "badger@ga.co", :password => "chicken", :password_confirmation => "chicken"

p "User count: #{User.all.count}"
p u1

Collection.destroy_all

m1 = Collection.create :user_id => u1.id
m2 = Collection.create :user_id => u2.id
m3 = Collection.create :user_id => u3.id

Race.destroy_all

# r = Race.create :name => "", :description => "", :ability_increases => "", :age => "", :alignment => "", :size => "", :speed => "", :languages => "", :features => ""

r1 = Race.create :name => "Human", :description => "human-like being", :ability_increases => "+1 Str, Dex, Con, Int, Wis, Cha", :age => "16-60 years", :alignment => "Any alignment", :size => "Medium", :speed => "30 feet", :languages => "Common", :features => "Adaptable"
r2 = Race.create :name => "Elf", :description => "tall, pointy eared people", :ability_increases => "+2 Dex", :age => "Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old.", :alignment => "AElves love freedom, variety, and self-expression, so they lean strongly toward the gentler aspects of chaos. They value and protect others’ freedom as well as their own, and they are more often good than not.", :size => "Elves range from under 5 to over 6 feet tall and have slender builds. Your size is Medium.", :speed => "Your base walking speed is 30 feet.", :languages => "You can speak, read, and write Common and Elvish. Elvish is fluid, with subtle intonations and intricate grammar. Elven literature is rich and varied, and their songs and poems are famous among other races. Many bards learn their language so they can add Elvish ballads to their repertoires.", :features => "Darkvision. Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.<br />
Keen Senses. You have proficiency in the Perception skill.<br />
Fey Ancestry. You have advantage on saving throws against being charmed, and magic can’t put you to sleep.<br />
Trance. Elves don’t need to sleep. Instead, they meditate deeply, remaining semiconscious, for 4 hours a day. (The Common word for such meditation is “trance.”) While meditating, you can dream after a fashion; such dreams are actually mental exercises that have become reflexive through years of practice. After resting in this way, you gain the same benefit that a human does from 8 hours of sleep."
r3 = Race.create :name => "Dwarf", :description => "short, beardy people", :ability_increases => "+2 Con, +1 Str", :age => "16-80 years", :alignment => "Any lawful alignment", :size => "Medium", :speed => "20 feet", :languages => "Common and Dwarven", :features => "Infravision, find traps and Secret doors"

Profession.destroy_all

# c = Profession.create :name => "", :description => "", :hit_dice => "", :saving_throw => "", :prof_skills => "", :start_hit_points => "", :start_prof_bonus => "", :start_features => ""

c1 = Profession.create :name => "Fighter", :description => "A master of martial combat, skilled with a variety of weapons and armor.", :hit_dice => "d10", :saving_throw => "Str, Con or Dex", :prof_skills => "Blacksmith, animal handling", :start_hit_points => "10", :start_prof_bonus => "+2", :start_features => "All armor, shields, simple and martial weapons.<br />
Fighting Style: You adopt a particular style of fighting as your specialty. Choose one of the following options.<br />
-Archery. You gain a +2 bonus to attack rolls you make with ranged weapons.<br />
-Defense. While you are wearing armor, you gain a +1 bonus to AC.<br />
-Dueling. When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.<br />
-Great Weapon Fighting. When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll, even if the new roll is a 1 or a 2. The weapon must have the two-handed or versatile property for you to gain this benefit.<br />
-Protection. When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll. You must be wielding a shield.<br />
-Two-Weapon Fighting. When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack.<br />
Second Wind: You have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use a bonus action to regain hit points equal to 1d10 + your fighter level. Once you use this feature, you must finish a short or long rest before you can use it again."
c2 = Profession.create :name => "Wizard", :description => "Wizards are supreme magic-users, defined and united as a class by the spells they cast. Drawing on the subtle weave of magic that permeates the cosmos, wizards cast spells of explosive fire, arcing lightning, subtle deception, and brute-force mind control. Their magic conjures monsters from other planes of existence, glimpses the future, or turns slain foes into zombies. Their mightiest spells change one substance into another, call meteors down from the sky, or open portals to other worlds.<br />
Though the casting of a typical spell requires merely the utterance of a few strange words, fleeting gestures, and sometimes a pinch or clump of exotic materials, these surface components barely hint at the expertise attained after years of apprenticeship and countless hours of study.<br />
Wizards live and die by their spells. Everything else is secondary. They learn new spells as they experiment and grow in experience. They can also learn them from other wizards, from ancient tomes or inscriptions, and from ancient creatures (such as the fey) that are steeped in magic.<br />
Wizards’ lives are seldom mundane. The closest a wizard is likely to come to an ordinary life is working as a sage or lecturer in a library or university, teaching others the secrets of the multiverse. Other wizards sell their services as diviners, serve in military forces, or pursue lives of crime or domination.<br />
But the lure of knowledge and power calls even the most unadventurous wizards out of the safety of their libraries and laboratories and into crumbling ruins and lost cities. Most wizards believe that their counterparts in ancient civilizations knew secrets of magic that have been lost to the ages, and discovering those secrets could unlock the path to a power greater than any magic available in the present age.", :hit_dice => "d4", :saving_throw => "Int, Wis", :prof_skills => "Writing, being smart", :start_hit_points => "4", :start_prof_bonus => "+2", :start_features => "simple weapon proficiencies, cast spells"
c3 = Profession.create :name => "Rogue", :description => "A scoundrel and stealthy warrior who uses stealth and trickery to overcome obstacles and enemies.", :hit_dice => "d8", :saving_throw => "Dex, Int", :prof_skills => "lockpicking, pickpocket", :start_hit_points => "8", :start_prof_bonus => "+2", :start_features => "Light Armor, Simple Weapons, Hand crossbows, Longswords, Rapiers, Shortswords <br />
Sneak Attack: You know how to strike subtly and exploit a foe’s distraction. Once per turn, you can deal extra damage to one creature you hit with an attack if you have advantage on the attack roll. The attack must use a finesse or a ranged weapon.<br />
Thieves' Cant: During your rogue training you learned thieves’ cant, a secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation. Only another creature that knows thieves’ cant understands such messages. It takes four times longer to convey such a message than it does to speak the same idea plainly. In addition, you understand a set of secret signs and symbols used to convey short, simple messages, such as whether an area is dangerous or the territory of a thieves’ guild, whether loot is nearby, or whether the people in an area are easy marks or will provide a safe house for thieves on the run.<br />
Cunning Action: Starting at your second level, your quick thinking and agility allow you to move and act quickly. You can take a bonus action on each of your turns in combat. This action can be used only to take the Dash, Disengage, or Hide action."



Background.destroy_all

# b = Background.create :name => "", :description => "", :background_skills => "", :background_languages => "", :background_equipment => "", :feature => "", :characteristics => "", :personality_trait => ["", "", "", "", "", "", "", ""].sample, :ideal => ["", "", "", "", "", ""].sample, :bond => ["", "", "", "", "", "" ].sample, :flaw => ["", "", "", "", "", ""].sample

b1 = Background.create :name => "Acolyte", :description => "You have spent your life in the service of a temple to a specific god or pantheon of gods.<br />
You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine.<br />
You are not necessarily a cleric - performing sacred rites is not the same thing as channeling divine power.<br />
Choose a god, a pantheon of gods, or some other quasi-divine being and work with your DM to detail the nature of your religious service.<br />
Were you a lesser functionary in a temple, raised from childhood to assist the priests in the sacred rites?<br />
Or were you a high priest who suddenly experienced a call to serve your god in a different way?<br />
Perhaps you were the leader of a small cult outside of any established temple structure, or even an occult group that served a fiendish master that you now deny.", :background_skills => "Insight, Religion", :background_languages => "Two of your choice", :background_equipment => "A holy symbol (a gift to you when you entered the priesthood), a prayer book or prayer wheel, 5 sticks of incense, vestments, a set of common clothes, and a belt pouch containing 15 gp", :feature => "Shelter of the Faithful.<br />
As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity.<br />
You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells.<br />
Those who share your religion will support you (but only you) at a modest lifestyle.
You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there.<br />
This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home.<br />
While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple.", :characteristics => "Acolytes are shaped by their experience in temples or other religious communities. Their study of the history and tenets of their faith and their relationships to temples, shrines, or hierarchies affect their mannerisms and ideals. Their flaws might be some hidden hypocrisy or heretical idea, or an ideal or bond taken to an extreme.", :personality_trait => ["I idolize a particular hero of my faith, and constantly refer to that person’s deeds and example.", "I can find common ground between the fiercest enemies, empathizing with them and always working towards peace.", "I see omens in every event and action. The gods try to speak to us, we just need to listen.", "Nothing can shake my optimistic attitude.", "I quote (or misquote) sacred texts and proverbs in almost every situation.", "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.", "I've enjoyed fine food, drink, and high society among my temple’s elite. Rough living grates on me.", "I’ve spent so long in the temple that I have little practical experience dealing with people in the outside world."].sample, :ideal => ["Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld.", "Charity. I always try to help those in need, no matter what the personal cost.", "Change. We must help bring about the changes the gods are constantly working in the world.", "Power. I hope to one day rise to the top of my faith’s religious hierarchy.", "Faith. I trust that my deity will guide my actions, I have faith that if I work hard, things will go well.", "Aspiration. I seek to prove myself worthy of my god’s favor by matching my actions against his or her teachings."].sample, :bond => ["I would die to recover an ancient relic of my faith that was lost long ago.", "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.", "I owe my life to the priest who took me in when my parents died.", "Everything I do is for the common people.", "I will do anything to protect the temple where I served.", "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy." ].sample, :flaw => ["I judge others harshly, and myself even more severely.", "I put too much trust in those who wield power within my temple’s hierarchy.", "My piety sometimes leads me to blindly trust those that profess faith in my god.", "I am inflexible in my thinking.", "I am suspicious of strangers and expect the worst of them.", "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life."].sample
b2 = Background.create :name => "Charlatan", :description => "You have always had a way with people.<br />
You know what makes them tick, you can tease out their hearts' desires after a few minutes of conversation, and with a few leading questions you can read them like they were children's books.<br />
It’s a useful talent, and one that you’re perfectly willing to use for your advantage.
You know what people want and you deliver, or rather, you promise to deliver.
Common sense should steer people away from things that sound too good to be true, but common sense seems to be in short supply when you’re around.<br />
The bottle of pink-colored liquid will surely cure that unseemly rash, this ointment—nothing more than a bit of fat with a sprinkle of silver dust—can
restore youth and vigor, and there’s a bridge in the city that just happens to be for sale.<br />
These marvels sound implausible, but you make them sound like the real deal.<br /> Every charlatan has an angle he or she uses in preference to other schemes. " + ["I cheat at games of chance.", "I shave coins or forge documents.", "I insinuate myself into people’s lives to prey on their weakness and secure their fortunes.", "I put on new identities like clothes.", "I run sleight-of-hand cons on street corners.", "I convince people that worthless junk is worth their hard-earned money."].sample, :background_skills => "Deception, Sleight of Hand", :background_languages => "Disguise Kit, Forgery Kit", :background_equipment => "A set of fine clothes, a disguise kit, tools of the con of your choice (ten stoppered bottles filled with colored liquid, a set of weighted dice, a deck of marked cards, or a signet ring of an imaginary duke), and a belt pouch containing 15 gp", :feature => "False Identity.<br />
You have created a second identity that includes documentation, established acquaintances, and disguises that allow you to assume that persona.<br />
Additionally, you can forge documents including official papers and personal letters, as long as you have seen an example of the kind of document or the handwriting you are trying to copy.", :characteristics => "Charlatans are colorful characters who conceal their true selves behind the masks they construct.<br />
They reflect what people want to see, what they want to believe, and how they see the world.<br />
But their true selves are sometimes plagued by an uneasy conscience, an old enemy, or deep-seated trust issues.", :personality_trait => ["I fall in and out of love easily, and am always pursuing someone.", "I have a joke for every occasion, especially occasions where humor is inappropriate.", "Flattery is my preferred trick for getting what I want.", "I’m a born gambler who can't resist taking a risk for a potential payoff.", "I lie about almost everything, even when there’s no good reason to.", "Sarcasm and insults are my weapons of choice.", "I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.", "I pocket anything I see that might have some value."].sample, :ideal => ["Independence. I am a free spirit— no one tells me what to do. ", "Fairness. I never target people who can’t afford to lose a few coins. ", "Charity. I distribute the money I acquire to the people who really need it.", "Creativity. I never run the same con twice.", "Friendship. Material goods come and go. Bonds of friendship last forever.", "Aspiration. I’m determined to make something of myself."].sample, :bond => ["I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.", "I owe everything to my mentor—a horrible person who’s probably rotting in jail somewhere.", "Somewhere out there, I have a child who doesn’t know me.
I’m making the world better for him or her.", "I come from a noble family, and one day I’ll reclaim my lands and title from those who stole them from me.", "A powerful person killed someone I love. Some day soon, I’ll have my revenge.", "I swindled and ruined a person who didn’t deserve it. I seek to atone for my misdeeds but might never be able to forgive myself." ].sample, :flaw => ["I can’t resist a pretty face.", "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.", "I’m convinced that no one could ever fool me the way I fool others.", "I’m too greedy for my own good. I can’t resist taking a risk if there’s money involved.", "I can’t resist swindling people who are more powerful than me.", "I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough."].sample
b3 = Background.create :name => "Criminal", :description => "You are an experienced criminal with a history of breaking the law.<br />
You have spent a lot of time among other criminals and still have contacts within the criminal underworld.<br />
You’re far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization, and you have survived up to this point by flouting the rules and regulations of society. Variant: Spy.<br />
Although your capabilities are not much different from those of a burglar or smuggler, you learned and practiced them in a very different context: as an espionage agent.
You might have been an officially sanctioned agent of the crown, or perhaps you sold the secrets you uncovered to the highest bidder.<br />
There are many kinds of criminals, and within a thieves’ guild or similar criminal organization, individual members have particular specialties. Even criminals who operate outside of such organizations have strong preferences for certain kinds of crimes over others.<br />
You are a " + ["Blackmailer", "Burglar", "Enforcer", "Fence", "Highway robber", "Hired killer", "Pickpocket", "Smuggler"].sample, :background_skills => "Deception, Stealth", :background_languages => "One type of gaming set, thieves’ tools", :background_equipment => "A crowbar, a set of dark common clothes including a hood, and a belt pouch containing 15 GP", :feature => "Criminal contact. You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals.
You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you.", :characteristics => "Criminals might seem like villains on the surface, and many of them are villainous to the core.
But some have an abundance of endearing, if not redeeming, characteristics.
There might be honor among thieves, but criminals rarely show any respect for law or authority.", :personality_trait => ["I always have a plan for what to do when things go wrong.", "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.", "The first thing I do in a new place is note the locations of everything valuable-or where such things could be hidden.", "I would rather make a new friend then a new enemy.", "I am increadibly slow to trust. Those who seem the fairest often have the most to hide.", "I don't pay attention to the risks in a situation. Never tell me the odds.", "The best way to get me to do something is to tell me I can't do it.", "I blow up at the slightest insult."].sample, :ideal => ["Honor. I don’t steal from others in the trade.", "Freedom. Chains are meant to be broken, as are those who would forge them.", "Charity. I steal from the wealthy so that I can help people in need. ", "Greed. I will do whatever it takes to become wealthy.", "People. I’m loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care.", "Redemption. There’s a spark of good in everyone."].sample, :bond => ["I’m trying to pay off an old debt I owe to a generous benefactor.", "My ill-gotten gains go to support my family.", "Something important was taken from me, and I aim to steal it back.", "I will become the greatest thief that ever lived.", "I’m guilty of a terrible crime. I hope I can redeem myself for it.", "Someone I loved died because of a mistake I made. That will never happen again." ].sample, :flaw => ["When I see something valuable, I can’t think about anything but how to steal it.", "When faced with a choice between money and my friends, I usually choose the money.", "If there’s a plan, I’ll forget it. If I don’t forget it, I’ll ignore it.", "I have a “tell” that reveals when I'm lying.", "I turn tail and run when things look bad.", "An innocent person is in prison for a crime that I committed. I’m okay with that."].sample
